const SET_MODE = "SET_MODE";
const SET_CARDS_AMOUNT = "SET_CARDS_AMOUNT";
const SET_CARDS = "SET_CARDS";
const CLICK_ON_CARD = "CLICK_ON_CARDS";
const CARDS_GUESSED = "CARDS_GUESSED";
const CLOSE_CARDS = "CLOSE_CARDS";
const ALL_CARDS_GUESSED = "ALL_CARDS_GUESSED";
const START_GAME = "START_GAME";
const SET_TIMER = "SET_TIMER";
const RESET_TIMER = "RESET_TIMER";

export {
  SET_MODE,
  SET_CARDS_AMOUNT,
  SET_CARDS,
  CLICK_ON_CARD,
  CARDS_GUESSED,
  CLOSE_CARDS,
  ALL_CARDS_GUESSED,
  START_GAME,
  SET_TIMER,
  RESET_TIMER,
};
